# Generated by Django 3.2.16 on 2022-12-22 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('one', 'single'), ('two', 'double'), ('multi', 'family')], max_length=6)),
                ('number', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
