# Generated by Django 3.2.16 on 2022-12-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0004_alter_room_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='category',
            field=models.CharField(choices=[('one', 'single'), ('two', 'double'), ('multi', 'family')], max_length=6),
        ),
    ]
